<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" ng-app="##APP_ANGULAR_APP_NAME##"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" ng-app="##APP_ANGULAR_APP_NAME##"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" ng-app="##APP_ANGULAR_APP_NAME##"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" ng-app="##APP_ANGULAR_APP_NAME##"> <!--<![endif]-->
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>Titel</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <base href="##APP_BASE_URI##">
    <link rel="stylesheet" type="text/css" href="app/styles/main.css">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  </head>
    <!--[if lt IE 7]>
      <p class="chromeframe">Sie verwenden einen alten Browser. <a href="http://browsehappy.com/?locale=de">Aktualisieren Sie noch heute Ihren Browser</a>
      oder <a href="http://www.google.com/chromeframe/?redirect=true">installieren Sie Google Chrome Frame</a> um diese Seite korrekt anzuzeigen.</p>
    <![endif]-->

    <!--[if lt IE 9]>
      <script src="app/components/es5-shim/es5-shim.js"></script>
      <script src="app/components/json3/lib/json3.min.js"></script>
    <![endif]-->

    <?php echo $this->getContent(); ?>

    <script src="app/components/angular/angular.js"></script>
    <script src="app/components/angular-resource/angular-resource.js"></script>
    <script src="app/components/angular-cookies/angular-cookies.js"></script>
    <script src="app/components/angular-sanitize/angular-sanitize.js"></script>

    <!-- build:js scripts/scripts.js -->
    <script src="app/scripts/app.js"></script>
    <script src="app/scripts/controllers/main.js"></script>
    <!-- endbuild -->
  </body>
</html>
